document.writeln("    <br id='Contact'>")
document.writeln('')
document.writeln("    <div class='container-fluid  py-2 wow fadeIn' data-wow-delay='0.1s'>")
document.writeln("        <div class='container py-5'>")
document.writeln("            <div class='section-title mb-5'>")
document.writeln("                <div class='sub-style'>")
document.writeln("                    <h4 class='sub-title px-3 mb-0'>Contact Us</h4>")
document.writeln('                </div>')
document.writeln("                <h2 class='mt-4 mb-4 fw-bold'>聯絡我們</h2>")
document.writeln('            </div>')
document.writeln("            <section id='contact'>")
document.writeln("                <div class='container-fluid' data-aos='fade-up'>")
document.writeln('')
document.writeln("                    <div class='row'>")
document.writeln('')
document.writeln("                        <div class='col-lg-6'>")
document.writeln("                            <div class='map mb-4 mb-lg-0'>")
document.writeln('                                <iframe')
document.writeln(
  "                                    src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3617.5293347516936!2d121.13233400000001!3d24.948098999999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3468255448390851%3A0xdf9ff595659fceb5!2z6byO5bGF5L2P5a6_6ZW354Wn5qmf5qeL!5e0!3m2!1szh-TW!2stw!4v1717208602586!5m2!1szh-TW!2stw'"
)
document.writeln("                                    frameborder='0' style='border:0; width: 100%; height: 340px;'></iframe>")
document.writeln('                            </div>')
document.writeln('                        </div>')
document.writeln('')
document.writeln("                        <div class='col-lg-6'>")
document.writeln("                            <div class='row'>")
document.writeln("                                <div class='col-md-4 info'>")
document.writeln("                                    <i class='bi bi-geo-alt'></i>")
document.writeln('                                    <p>桃園市楊梅區高鐵南路七段178巷16號</p>')
document.writeln('                                </div>')
document.writeln("                                <div class='col-md-4 info'>")
document.writeln("                                    <i class='bi bi-envelope'></i>")
document.writeln('                                    <p>dingjuhappy99@gmail.com</p>')
document.writeln('                                </div>')
document.writeln("                                <div class='col-md-4 info'>")
document.writeln("                                    <i class='bi bi-telephone'></i>")
document.writeln('                                    <p>03-2888-666</p>')
document.writeln('                                </div>')
document.writeln('                            </div>')
document.writeln('')
document.writeln("                            <div class='form'>")
document.writeln("                                <form action='forms/contact.php' method='post' role='form' class='php-email-form'>")
document.writeln("                                    <div class='row'>")
document.writeln('')
document.writeln("                                        <div class='form-group col-lg-6'>")
document.writeln("                                            <input type='text' name='name' class='form-control' id='name'")
document.writeln("                                                placeholder='入住者姓名' required>")
document.writeln('                                        </div>')
document.writeln("                                        <div class='form-group col-lg-6 mt-3 mt-lg-0'>")
document.writeln("                                            <input type='text' class='form-control'  id='name2'")
document.writeln("                                                placeholder='聯絡人姓名' required>")
document.writeln('                                        </div>')
document.writeln('                                    </div>')
document.writeln("                                    <div class='form-group mt-3'>")
document.writeln("                                        <input type='text' class='form-control' name='subject' id='subject'")
document.writeln("                                            placeholder='聯絡人電話' required>")
document.writeln('                                    </div>')
document.writeln("                                    <div class='form-group mt-3'>")
document.writeln("                                        <textarea class='form-control' name='message' rows='5' placeholder='請簡單描述住民需求或家屬需求:'")
document.writeln('                                            required></textarea>')
document.writeln('                                    </div>')
document.writeln("                                    <div class='my-3'>")
document.writeln("                                        <div class='loading'>Loading</div>")
document.writeln("                                        <div class='error-message'></div>")
document.writeln("                                        <div class='sent-message'>感謝您的洽詢，我們將盡快與您聯繫！</div>")
document.writeln('                                    </div>')
document.writeln('')
document.writeln("                                    <div class='text-center '>")
document.writeln("                                        <a href='#' class='btn btn-primary rounded-pill text-white py-3 px-5'>送出</a>")
document.writeln('                                    </div>')
document.writeln('                                </form>')
document.writeln('')
document.writeln('                            </div>')
document.writeln('                        </div>')
document.writeln('')
document.writeln('                    </div>')
document.writeln('')
document.writeln('                </div>')
document.writeln('            </section>')
document.writeln('        </div>')
document.writeln('    </div>')

document.writeln('    <!-- Footer Start -->')
document.writeln("    <div class='container-fluid footer py-2 wow fadeIn text-white' data-wow-delay='0.2s'>")
document.writeln("        <div class='container '>")
document.writeln("            <div class='row g-5'>")
document.writeln("                <div class='col-12 col-md-4 py-2'>")
document.writeln("                    <div class='footer-item d-flex flex-column'>")
document.writeln("                        <img class='logo' src='./img/logo-01-02.png' alt=''>")
document.writeln('')
document.writeln('                    </div>')
document.writeln('                </div>')
document.writeln('')
document.writeln("                <div class='col-12 col-md-8 py-2'>")
document.writeln("                    <div class='footer-item d-flex flex-column'>")
document.writeln("                        <h5 class='text-white'>基礎忠恕長照財團法人附設桃園市私立鼎居住宿長照機構</h5>")
document.writeln("                        <h6 class='text-white mb-2'>Ding Ju Residential Long-term Care Institutions of Ji Chu Zhong Shu")
document.writeln('                            Long-Term Care Foundation Institutions</h6>')
document.writeln("                        <a><i class='fa fa-map-marker-alt me-2'></i>桃園市楊梅區高鐵南路七段178巷16號</a>")
document.writeln("                        <a href='mailto:dingjuhappy99@gmail.com'><i")
document.writeln("                                class='fas fa-envelope me-2'></i>dingjuhappy99@gmail.com</a>")
document.writeln("                        <a><i class='bi bi-telephone-fill me-2'></i>03-2888-666</a>")
document.writeln('                    </div>')
document.writeln('                </div>')
document.writeln("                <div class='ft_copyright m-auto'>")
document.writeln("                    <span><a href='../privacy.html'>隱私權政策　</a>")
document.writeln('                    </span>')
document.writeln('                    <span>')
document.writeln('                        <small>© Copyright 2024')
document.writeln('                            Ji Chu Zhong Shu')
document.writeln('                            Ding Ju Residential Long-term Care Institutions of Ji Chu Zhong Shu Long-Term Care')
document.writeln('                            Foundation Institutions')
document.writeln('                            All Rights Reserved.</small>')
document.writeln('                    </span>')
document.writeln('                </div>')
document.writeln('            </div>')
document.writeln('        </div>')
document.writeln('    </div>')
document.writeln('    <!-- Footer End -->')
