document.writeln("        <nav class='navbar navbar-expand-lg navbar-light bg-white px-4 px-lg-5 py-2 py-lg-0'>")
document.writeln("            <a href='index.html' class='navbar-brand p-0'>")
document.writeln("                <img src='img/logo-01.png' alt='Logo'>")
document.writeln('            </a>')
document.writeln("            <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarCollapse'>")
document.writeln("                <span class='fa fa-bars'></span>")
document.writeln('            </button>')
document.writeln("            <div class='collapse navbar-collapse' id='navbarCollapse'>")
document.writeln("                <div class='navbar-nav ms-auto py-0'>")
document.writeln("                    <a id='nav_01' href='index.html' class='nav-item nav-link '>首頁</a>")
document.writeln("                    <a id='nav_02' href='about.html' class='nav-item nav-link'>關於鼎居</a>")
document.writeln("                    <div class='nav-item dropdown'>")
document.writeln("                        <a id='nav_03' href='#' class='nav-link dropdown-toggle' data-bs-toggle='dropdown'>服務介紹</a>")
document.writeln("                        <div class='dropdown-menu m-0'>")
document.writeln("                            <a href='introduction.html' class='dropdown-item'>環境介紹/特色</a>")
document.writeln("                            <a href='fee.html' class='dropdown-item'>收費標準</a>")
document.writeln("                            <!-- <a href='blog.html' class='dropdown-item'>機構特色</a> -->")
document.writeln('                        </div>')
document.writeln('                    </div>')
document.writeln("                    <a id='nav_04' href='https://www.facebook.com/profile.php?id=100069498739743&ref=embed_page'")
document.writeln("                        class='nav-item nav-link' target='_blank'>最新消息</a>")
document.writeln("                    <a id='nav_05' href='contact.html' class='nav-item nav-link'>探訪須知</a>")
document.writeln("                    <a id='nav_06' href='info.html' class='nav-item nav-link'>入住流程</a>")
document.writeln('                </div>')
document.writeln("                <a href='#Contact'")
document.writeln("                    class='btn btn-primary rounded-pill text-white py-2 px-4 flex-wrap flex-sm-shrink-0'>聯絡我們</a>")
document.writeln('            </div>')
document.writeln('        </nav>')
